import Link from "next/link"

interface EmailExample {
  subject: string
  preview: string
}

interface FAQItem {
  question: string
  answer: string
}

export interface VerticalContent {
  vertical: string
  verticalSlug: string
  heroTagline: string
  heroDescription: string
  painPoints: {
    title: string
    description: string
    stat?: string
    statSource?: string
  }[]
  beforeEmail: { subject: string; body: string }
  afterEmail: { subject: string; body: string }
  exampleSequence: EmailExample[]
  steps: { title: string; description: string }[]
  faqs: FAQItem[]
}

export function VerticalLanding({ content }: { content: VerticalContent }) {
  return (
    <div className="min-h-screen bg-[#fafafa]">
      {/* Nav */}
      <nav className="max-w-3xl mx-auto px-6 py-6 flex items-center justify-between">
        <Link href="/" className="text-lg font-bold text-gray-900">
          ColdCopy
        </Link>
        <Link
          href="/"
          className="text-sm text-gray-500 hover:text-gray-900 transition-colors"
        >
          Try free &rarr;
        </Link>
      </nav>

      <main className="max-w-3xl mx-auto px-6 pb-20">
        {/* Hero */}
        <section className="py-12 space-y-4">
          <div className="inline-flex items-center gap-2 bg-gray-100 text-gray-600 text-xs font-medium px-3 py-1.5 rounded-full">
            <span className="w-1.5 h-1.5 bg-green-500 rounded-full" />
            Cold email that gets replies
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 leading-tight">
            Cold Email Sequences for {content.vertical} Brands
          </h1>
          <p className="text-lg text-gray-500 max-w-2xl">
            {content.heroDescription}
          </p>
          <Link
            href="/"
            className="inline-block bg-gray-900 hover:bg-gray-700 text-white font-semibold px-6 py-3 rounded-xl transition-colors"
          >
            Try free — no signup
          </Link>
        </section>

        {/* Why [Vertical] Brands Need Cold Outreach */}
        <section className="py-12 border-t border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">
            Why {content.vertical} Brands Need Cold Outreach
          </h2>
          <div className="space-y-6">
            {content.painPoints.map((point, i) => (
              <div key={i} className="bg-white rounded-xl p-6 border border-gray-200">
                <h3 className="font-semibold text-gray-900 mb-2">{point.title}</h3>
                <p className="text-gray-600 text-sm leading-relaxed">{point.description}</p>
                {point.stat && (
                  <p className="text-xs text-gray-400 mt-3">
                    {point.stat}
                    {point.statSource && <> — {point.statSource}</>}
                  </p>
                )}
              </div>
            ))}
          </div>
        </section>

        {/* Before/After */}
        <section className="py-12 border-t border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">
            What a Good {content.vertical} Cold Email Looks Like
          </h2>
          <div className="grid sm:grid-cols-2 gap-4">
            <div className="bg-red-50 border border-red-200 rounded-xl p-5">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-red-500 text-lg">✗</span>
                <span className="text-sm font-semibold text-red-700">Generic template</span>
              </div>
              <p className="text-xs text-gray-500 mb-1">Subject: {content.beforeEmail.subject}</p>
              <p className="text-sm text-gray-600 whitespace-pre-line leading-relaxed">
                {content.beforeEmail.body}
              </p>
            </div>
            <div className="bg-green-50 border border-green-200 rounded-xl p-5">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-green-500 text-lg">✓</span>
                <span className="text-sm font-semibold text-green-700">ColdCopy output</span>
              </div>
              <p className="text-xs text-gray-500 mb-1">Subject: {content.afterEmail.subject}</p>
              <p className="text-sm text-gray-600 whitespace-pre-line leading-relaxed">
                {content.afterEmail.body}
              </p>
            </div>
          </div>
        </section>

        {/* Example sequence */}
        <section className="py-12 border-t border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900 mb-2">
            Sample 5-Email Sequence
          </h2>
          <p className="text-gray-500 text-sm mb-6">
            Generated by ColdCopy in 8 seconds from a real {content.vertical.toLowerCase()} brand URL.
          </p>
          <div className="space-y-3">
            {content.exampleSequence.map((email, i) => (
              <div key={i} className="bg-white rounded-xl p-4 border border-gray-200 flex items-start gap-3">
                <span className="text-xs font-mono text-gray-400 mt-0.5 shrink-0">
                  {i + 1}
                </span>
                <div>
                  <p className="text-sm font-medium text-gray-900">{email.subject}</p>
                  <p className="text-xs text-gray-500 mt-1">{email.preview}</p>
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* How ColdCopy Works */}
        <section className="py-12 border-t border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">
            How ColdCopy Works for {content.vertical} Brands
          </h2>
          <div className="space-y-4">
            {content.steps.map((step, i) => (
              <div key={i} className="flex items-start gap-4">
                <span className="shrink-0 w-8 h-8 rounded-full bg-gray-900 text-white flex items-center justify-center text-sm font-bold">
                  {i + 1}
                </span>
                <div>
                  <h3 className="font-semibold text-gray-900">{step.title}</h3>
                  <p className="text-sm text-gray-600 mt-1">{step.description}</p>
                </div>
              </div>
            ))}
          </div>
          <div className="mt-8">
            <Link
              href="/"
              className="inline-block bg-gray-900 hover:bg-gray-700 text-white font-semibold px-6 py-3 rounded-xl transition-colors"
            >
              Try it now — paste any {content.vertical.toLowerCase()} brand URL
            </Link>
          </div>
        </section>

        {/* FAQ */}
        <section className="py-12 border-t border-gray-200">
          <h2 className="text-2xl font-bold text-gray-900 mb-6">
            Frequently Asked Questions
          </h2>
          <div className="space-y-4">
            {content.faqs.map((faq, i) => (
              <details key={i} className="bg-white rounded-xl border border-gray-200 group">
                <summary className="p-5 cursor-pointer text-sm font-medium text-gray-900 list-none flex items-center justify-between">
                  {faq.question}
                  <span className="text-gray-400 group-open:rotate-45 transition-transform text-lg">+</span>
                </summary>
                <div className="px-5 pb-5 text-sm text-gray-600 leading-relaxed">
                  {faq.answer}
                </div>
              </details>
            ))}
          </div>
        </section>

        {/* Final CTA */}
        <section className="py-12 border-t border-gray-200 text-center">
          <h2 className="text-2xl font-bold text-gray-900 mb-3">
            Write your first {content.vertical.toLowerCase()} cold email sequence
          </h2>
          <p className="text-gray-500 mb-6">One free sequence. No signup. No credit card. 8 seconds.</p>
          <Link
            href="/"
            className="inline-block bg-gray-900 hover:bg-gray-700 text-white font-semibold px-8 py-4 rounded-xl transition-colors text-lg"
          >
            Try ColdCopy free
          </Link>
          <p className="text-xs text-gray-400 mt-4">
            $19/month for unlimited sequences after your free trial. Cancel anytime.
          </p>
        </section>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-200 py-8">
        <div className="max-w-3xl mx-auto px-6 flex items-center justify-between text-xs text-gray-400">
          <span>ColdCopy</span>
          <div className="flex gap-4">
            <Link href="/privacy" className="hover:text-gray-600">Privacy</Link>
            <Link href="/terms" className="hover:text-gray-600">Terms</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
